

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        retryer: com.example.demo.config.NarvarRetryer

  metrics:
    enabled: true
resilience4j:
  circuitbreaker:
    instances:
      demo:
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 3
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        slowCallRateThreshold: 100




narvar:
  url: https://ws-st01.narvar.qa/api/v1
  retryMaxAttempts: 5
  retryInterval: 3000